### ISSUE TITLE
Differentiating between empty cell and cell with value 0

### ISSUE THREAD

**Issue by daryomizrahi** [miyako/4d-plugin-free-xl#1]
Hi, I am Daryo and we have met at 4D summit in Paris last week. As you have suggested, I am opening an issue here about return value in FreeXL.
When I use FreeXL_Get_cell_value to get the value of a cell, I would like to differentiate between an excel cell that is empty and one with numeric cell value of 0. Right now both cases return 0 as integer, 0 as real, and empty string.
Thank you for your help.

The command:
$error:=FreeXL_Get_cell_value ($ref;$r;$c;$integer;$real;$text)

**Comment by miyako** [comment]
$error is -22 if the cell is empty. does that answer your need?

**Comment by daryomizrahi** [comment]
Yes, exactly what I needed!
Thank you very much.
Daryo
